apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bpefgj9bt-python 
  janus-idp.io/tekton: bpefgj9bt-python
  backstage.io/kubernetes-id: bpefgj9bt-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bpefgj9bt-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml