apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bpefgj9bt-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bpefgj9bt-python 
  name: bpefgj9bt-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bpefgj9bt-python 
